package com.apkpure.components.greendao.db;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.apkpure.components.downloader.db.bean.MissionDbBean;

import com.apkpure.components.greendao.db.MissionDbBeanDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig missionDbBeanDaoConfig;

    private final MissionDbBeanDao missionDbBeanDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        missionDbBeanDaoConfig = daoConfigMap.get(MissionDbBeanDao.class).clone();
        missionDbBeanDaoConfig.initIdentityScope(type);

        missionDbBeanDao = new MissionDbBeanDao(missionDbBeanDaoConfig, this);

        registerDao(MissionDbBean.class, missionDbBeanDao);
    }
    
    public void clear() {
        missionDbBeanDaoConfig.clearIdentityScope();
    }

    public MissionDbBeanDao getMissionDbBeanDao() {
        return missionDbBeanDao;
    }

}
