package com.apkpure.components.greendao.db;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.apkpure.components.downloader.db.bean.DownloadTask2;

import com.apkpure.components.greendao.db.DownloadTask2Dao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig downloadTask2DaoConfig;

    private final DownloadTask2Dao downloadTask2Dao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        downloadTask2DaoConfig = daoConfigMap.get(DownloadTask2Dao.class).clone();
        downloadTask2DaoConfig.initIdentityScope(type);

        downloadTask2Dao = new DownloadTask2Dao(downloadTask2DaoConfig, this);

        registerDao(DownloadTask2.class, downloadTask2Dao);
    }
    
    public void clear() {
        downloadTask2DaoConfig.clearIdentityScope();
    }

    public DownloadTask2Dao getDownloadTask2Dao() {
        return downloadTask2Dao;
    }

}
