package com.apkpure.components.greendao.db;

import android.database.Cursor;
import android.database.sqlite.SQLiteStatement;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.internal.DaoConfig;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseStatement;

import com.apkpure.components.downloader.db.other.TaskStatus;
import com.apkpure.components.downloader.db.other.TaskStatusConverter;

import com.apkpure.components.downloader.db.bean.DownloadTask;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "downloadTask".
*/
public class DownloadTaskDao extends AbstractDao<DownloadTask, String> {

    public static final String TABLENAME = "downloadTask";

    /**
     * Properties of entity DownloadTask.<br/>
     * Can be used for QueryBuilder and for referencing column names.
     */
    public static class Properties {
        public final static Property DownloadUrl = new Property(0, String.class, "downloadUrl", true, "_download_url");
        public final static Property ShortName = new Property(1, String.class, "shortName", false, "_short_name");
        public final static Property AbsolutePath = new Property(2, String.class, "absolutePath", false, "_absolute_path");
        public final static Property ParamData = new Property(3, String.class, "paramData", false, "_param_date");
        public final static Property TaskStatus = new Property(4, Integer.class, "taskStatus", false, "_task_status_type");
        public final static Property Date = new Property(5, java.util.Date.class, "date", false, "_date");
        public final static Property CurrentOffset = new Property(6, long.class, "currentOffset", false, "_current_offset");
        public final static Property TotalLength = new Property(7, long.class, "totalLength", false, "_total_length");
        public final static Property Flag = new Property(8, int.class, "flag", false, "_flag");
        public final static Property Desc = new Property(9, String.class, "desc", false, "_desc");
    }

    private final TaskStatusConverter taskStatusConverter = new TaskStatusConverter();

    public DownloadTaskDao(DaoConfig config) {
        super(config);
    }
    
    public DownloadTaskDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(Database db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"downloadTask\" (" + //
                "\"_download_url\" TEXT PRIMARY KEY NOT NULL ," + // 0: downloadUrl
                "\"_short_name\" TEXT," + // 1: shortName
                "\"_absolute_path\" TEXT," + // 2: absolutePath
                "\"_param_date\" TEXT," + // 3: paramData
                "\"_task_status_type\" INTEGER," + // 4: taskStatus
                "\"_date\" INTEGER," + // 5: date
                "\"_current_offset\" INTEGER NOT NULL ," + // 6: currentOffset
                "\"_total_length\" INTEGER NOT NULL ," + // 7: totalLength
                "\"_flag\" INTEGER NOT NULL ," + // 8: flag
                "\"_desc\" TEXT);"); // 9: desc
        // Add Indexes
        db.execSQL("CREATE UNIQUE INDEX " + constraint + "IDX_downloadTask__download_url ON \"downloadTask\"" +
                " (\"_download_url\" ASC);");
    }

    /** Drops the underlying database table. */
    public static void dropTable(Database db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"downloadTask\"";
        db.execSQL(sql);
    }

    @Override
    protected final void bindValues(DatabaseStatement stmt, DownloadTask entity) {
        stmt.clearBindings();
        stmt.bindString(1, entity.getDownloadUrl());
 
        String shortName = entity.getShortName();
        if (shortName != null) {
            stmt.bindString(2, shortName);
        }
 
        String absolutePath = entity.getAbsolutePath();
        if (absolutePath != null) {
            stmt.bindString(3, absolutePath);
        }
 
        String paramData = entity.getParamData();
        if (paramData != null) {
            stmt.bindString(4, paramData);
        }
 
        TaskStatus taskStatus = entity.getTaskStatus();
        if (taskStatus != null) {
            stmt.bindLong(5, taskStatusConverter.convertToDatabaseValue(taskStatus));
        }
 
        java.util.Date date = entity.getDate();
        if (date != null) {
            stmt.bindLong(6, date.getTime());
        }
        stmt.bindLong(7, entity.getCurrentOffset());
        stmt.bindLong(8, entity.getTotalLength());
        stmt.bindLong(9, entity.getFlag());
 
        String desc = entity.getDesc();
        if (desc != null) {
            stmt.bindString(10, desc);
        }
    }

    @Override
    protected final void bindValues(SQLiteStatement stmt, DownloadTask entity) {
        stmt.clearBindings();
        stmt.bindString(1, entity.getDownloadUrl());
 
        String shortName = entity.getShortName();
        if (shortName != null) {
            stmt.bindString(2, shortName);
        }
 
        String absolutePath = entity.getAbsolutePath();
        if (absolutePath != null) {
            stmt.bindString(3, absolutePath);
        }
 
        String paramData = entity.getParamData();
        if (paramData != null) {
            stmt.bindString(4, paramData);
        }
 
        TaskStatus taskStatus = entity.getTaskStatus();
        if (taskStatus != null) {
            stmt.bindLong(5, taskStatusConverter.convertToDatabaseValue(taskStatus));
        }
 
        java.util.Date date = entity.getDate();
        if (date != null) {
            stmt.bindLong(6, date.getTime());
        }
        stmt.bindLong(7, entity.getCurrentOffset());
        stmt.bindLong(8, entity.getTotalLength());
        stmt.bindLong(9, entity.getFlag());
 
        String desc = entity.getDesc();
        if (desc != null) {
            stmt.bindString(10, desc);
        }
    }

    @Override
    public String readKey(Cursor cursor, int offset) {
        return cursor.getString(offset + 0);
    }    

    @Override
    public DownloadTask readEntity(Cursor cursor, int offset) {
        DownloadTask entity = new DownloadTask( //
            cursor.getString(offset + 0), // downloadUrl
            cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1), // shortName
            cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2), // absolutePath
            cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3), // paramData
            cursor.isNull(offset + 4) ? null : taskStatusConverter.convertToEntityProperty(cursor.getInt(offset + 4)), // taskStatus
            cursor.isNull(offset + 5) ? null : new java.util.Date(cursor.getLong(offset + 5)), // date
            cursor.getLong(offset + 6), // currentOffset
            cursor.getLong(offset + 7), // totalLength
            cursor.getInt(offset + 8), // flag
            cursor.isNull(offset + 9) ? null : cursor.getString(offset + 9) // desc
        );
        return entity;
    }
     
    @Override
    public void readEntity(Cursor cursor, DownloadTask entity, int offset) {
        entity.setDownloadUrl(cursor.getString(offset + 0));
        entity.setShortName(cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1));
        entity.setAbsolutePath(cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2));
        entity.setParamData(cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3));
        entity.setTaskStatus(cursor.isNull(offset + 4) ? null : taskStatusConverter.convertToEntityProperty(cursor.getInt(offset + 4)));
        entity.setDate(cursor.isNull(offset + 5) ? null : new java.util.Date(cursor.getLong(offset + 5)));
        entity.setCurrentOffset(cursor.getLong(offset + 6));
        entity.setTotalLength(cursor.getLong(offset + 7));
        entity.setFlag(cursor.getInt(offset + 8));
        entity.setDesc(cursor.isNull(offset + 9) ? null : cursor.getString(offset + 9));
     }
    
    @Override
    protected final String updateKeyAfterInsert(DownloadTask entity, long rowId) {
        return entity.getDownloadUrl();
    }
    
    @Override
    public String getKey(DownloadTask entity) {
        if(entity != null) {
            return entity.getDownloadUrl();
        } else {
            return null;
        }
    }

    @Override
    public boolean hasKey(DownloadTask entity) {
        throw new UnsupportedOperationException("Unsupported for entities with a non-null key");
    }

    @Override
    protected final boolean isEntityUpdateable() {
        return true;
    }
    
}
